name: ChainStarter

on: 
  workflow_dispatch:




jobs:
  caller_job:
    runs-on: ubuntu-latest
    steps:
      - name: trace
        run: echo "starter (A) launched"

        

  running-nested:
    uses: Testing-Forecast-Actions/TEST_2/.github/workflows/chain_nested.yml@master
    # with:
    #   changes-list: ${{ needs. prepare-data-to-be-persisted.outputs.changed_files }}

    # secrets:
    #   envPAT: ${{ secrets.GITHUB_TOKEN }}
