  name: "PR_CREATE"
  on:
    workflow_dispatch:
    
  jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
        - name: trace step
          run: echo "Tracing test step"


        # Checkout the data repository
        # -------------------------------------------
        - name: checkout data repo
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            # repository: 'Testing-Forecast-Actions/TEST_2'
            # ref: 'master'
            # path: './repo/'

        - name: wget
          uses: wei/wget@v1
          with:
            args: -O pippo.csv google.com
            # args: -P ./repo -O pippo.csv google.com

        # - name: get a remote file
        #   run: |
        #     echo "Getting remote file"
        #     # wget ‐‐directory-prefix=./repo/ -O pippo.csv https://xmart-api-public.who.int/FLUMART/VIW_FID?$format=csv
        #     wget ‐‐directory-prefix=./repo/ -O pippo.csv google.com
  
  
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            # cwd: './repo'
            # author_name: PMi74
            # author_email: paolo.milano@gmail.com
            message: 'Testing commit'
            # add: '*.csv'

            
        - name: Create Pull Request
          id: cpr
          uses: peter-evans/create-pull-request@v3
          
        - name: Check outputs
          run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
            echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
  
        # - name: Open the pull requests
        #   run: |
        #     echo "Opening PR"
        #     gh pr create -B master --title 'Test merge' --body 'Created by Github action'
        #   env:
        #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
