name: RunOnPrevious

on:
  workflow_run:
    workflows: [test]
      
    types:
      - completed

  workflow_dispatch:

jobs:

  run_on_success:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'Testing-Forecast-Actions' }}
    runs-on: ubuntu-latest
    steps:


    - name: Trace starting
      id: trace_success
      run: echo "Run on successfull wf" 
