name: test
on:
  workflow_dispatch:



jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:

      # Checkout the python tools repo
      # used to authenticate and validate the PR
      # -------------------------------------------      
      - name: trace
        run: |
           echo "Variable BEFORE Value is ${{ vars.TEST_BOOL_VAR }}"


      - name: set var val
        run: |
          echo "TEST_BOOL_VAR = 'false'" >> "$GITHUB_VARS"

      - name: trace
        run: |
           echo "Variable AFTER Value is ${{ vars.TEST_BOOL_VAR }}"
