name: test
on:
  workflow_dispatch:



jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:

      # Checkout the python tools repo
      # used to authenticate and validate the PR
      # -------------------------------------------      
      - name: trace
        run: |
           echo "Variable BEFORE Value is ${{ vars.TEST_BOOL_VAR }}"

      - uses: actions/checkout@v3


      - name: set var val
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh variable list
          # gh variable set TEST_BOOL_VAR --body "false"

      - name: trace
        run: |
           echo "Variable AFTER Value is ${{ vars.TEST_BOOL_VAR }}"
