name: test
on:
  workflow_dispatch:



jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      IMPORT_NEEDED: 'true'
    
    steps:

      # Checkout the python tools repo
      # used to authenticate and validate the PR
      # -------------------------------------------      
      - name: trace
        run: |
           echo "Variable BEFORE Value is ${{ env.IMPORT_NEEDED }}"

      - uses: actions/checkout@v3


      - name: set var val
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "IMPORT_NEEDED='false'" >> $GITHUB_ENV

          
      - name: trace
        run: |
           echo "Variable AFTER Value is ${{ env.IMPORT_NEEDED }}"
