  name: TestPrWf

  on:
    workflow_dispatch:


  jobs:
    test_job:
      runs-on: ubuntu-latest


      steps:
        - name: trace step
          run: echo "Tracing test step"


        # Checkout the data repository
        # -------------------------------------------
        # - name: checkout data repo
        #   uses: actions/checkout@v3
        #   with:
        #     token: ${{ secrets.GITHUB_TOKEN }}
        #     repository: 'Testing-Forecast-Actions/TEST_2'
        #     ref: 'master'
        #     path: './repo/'
  
        - name: checkout data repo
          uses: actions/checkout@v3
          with:          
            token: ${{ secrets.GITHUB_TOKEN }}  


        - name: wget
          uses: wei/wget@v1
          with:
            args: -O test.csv google.com
              
  
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:  
            message: 'Testing commit'
            new_branch: my-branch
        
        - name: Open the pull requests
          run: |
            echo "Opening PR"
            gh pr create --title 'Test merge' --body 'Created by Github action'
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
